[package]
name = "speedwayrs-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
wasm-logger="0.2.0"
sycamore = "0.8.2"
sycamore-router = "0.8.0"